# Uncomment the next line to define a global platform for your project
platform :ios, '9.3'

target 'HohokamDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks

  #use_frameworks!
  pod 'ViroReact', :path => '../node_modules/react-viro/ios/'
  #pod 'ViroKit', :path => '../node_modules/react-viro/ios/dist/ViroRenderer/'
  pod 'ViroKit_static_lib', :path => '../node_modules/react-viro/ios/dist/ViroRenderer/static_lib'

end
